| **Category**   | **Description**                                                | **Control Type** | **Purpose**                                            | **Example**                                |
|-----------------|----------------------------------------------------------------|------------------|--------------------------------------------------------|--------------------------------------------|
| **Technical**   | Uses technology to protect systems or information.            | Preventive       | Stops problems before they happen.                    | Firewall (blocks unauthorized access).     |
|                 |                                                                | Deterrent        | Discourages or warns against misuse.                  | Splash screen (shows warning message).     |
|                 |                                                                | Detective        | Detects problems when they occur.                     | System logs (records system activities).   |
|                 |                                                                | Corrective       | Fixes issues after they happen.                       | Backup recovery (restores lost data).      |
|                 |                                                                | Compensating     | Acts as a temporary measure if a full solution isn't in place. | Block instead of patch (temporary block).  |
|                 |                                                                | Directive        | Provides instructions for secure actions.             | File storage policies (guidelines for file management). |
| **Managerial**  | Involves policies, rules, and management practices that guide secure behavior. | Preventive       | Sets guidelines to avoid problems from the start.     | Onboarding policy (securely introduces new employees). |
|                 |                                                                | Deterrent        | Warns of consequences for inappropriate actions.       | Demotion (possible penalty for misuse).    |
|                 |                                                                | Detective        | Helps to identify security issues by reviewing actions. | Review login reports (checks for unusual logins). |
|                 |                                                                | Corrective       | Provides guidance on how to fix or report problems.    | Reporting policy (explains how to report issues). |
|                 |                                                                | Compensating     | Ensures that responsibilities are spread out to reduce risk. | Separation of duties (different people handle different tasks). |
|                 |                                                                | Directive        | Sets compliance standards or guidelines to follow.     | Compliance policies (rules to meet legal requirements). |
| **Operational** | Daily procedures and practices that support security.         | Preventive       | Uses physical security measures to prevent unauthorized access. | Guard shack (guards control entry).       |
|                 |                                                                | Deterrent        | Has a visible security presence to discourage unauthorized access. | Reception desk (front desk presence).   |
|                 |                                                                | Detective        | Monitors for security issues during day-to-day activities. | Property patrols (check for unusual activities). |
|                 |                                                                | Corrective       | Contacts authorities or takes action when issues arise. | Contact authorities (calls police if needed). |
|                 |                                                                | Compensating     | Adds extra security staff to cover areas with higher risk. | Multiple security staff (more coverage). |
|                 |                                                                | Directive        | Provides training to staff about security practices and policies. | Security training (teaches security policies). |
| **Physical**    | Physical measures to control access to buildings, rooms, or equipment. | Preventive       | Locks doors and physical barriers to stop unauthorized entry. | Door lock (prevents entry).               |
|                 |                                                                | Deterrent        | Puts up signs or warnings to keep people aware of restricted areas. | Warning signs (inform of restricted areas). |
|                 |                                                                | Detective        | Uses devices to detect unauthorized movement in certain areas. | Motion detectors (detect movement).      |
|                 |                                                                | Corrective       | Provides tools to handle emergencies.                  | Fire extinguisher (puts out fires).        |
|                 |                                                                | Compensating     | Provides backup power or other alternatives if main resources are unavailable. | Power generator (backup power source).    |
|                 |                                                                | Directive        | Puts up signs or labels that tell who can access certain areas. | "Authorized Personnel Only" signs.       |
